### ISSUE TITLE
Question - How to use with browserify

### ISSUE THREAD

**Issue by nearAP** [crocodilejs/custom-fonts-in-emails#1]
Hi,

How do I use this with browserify?

When I run - `browserify my_source.js -o my_output.js`

where 'my_source.js' includes the import command for custom-fonts-in-email, I get the following error - _import declarations may only occur at top level of a module_

**Comment by niftylettuce** [comment]
I do not believe you can use this client-side due to the `sharp` dependency.  The warning about import declarations must be an issue with your linting.

**Comment by nearAP** [comment]
K. Thanks
